import type { Task, Note, Invoice } from '@/types'
import { db } from '@/lib/db'

export async function exportToJSON(data: any): Promise<Blob> {
  const json = JSON.stringify(data, null, 2)
  return new Blob([json], { type: 'application/json' })
}

export async function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export async function exportTasks(): Promise<void> {
  const tasks = await db.tasks.toArray()
  const blob = await exportToJSON(tasks)
  await downloadBlob(blob, `tasks-export-${Date.now()}.json`)
}

export async function exportNotes(): Promise<void> {
  const notes = await db.notes.toArray()
  const blob = await exportToJSON(notes)
  await downloadBlob(blob, `notes-export-${Date.now()}.json`)
}

export async function exportAll(): Promise<void> {
  const data = {
    tasks: await db.tasks.toArray(),
    notes: await db.notes.toArray(),
    projects: await db.projects.toArray(),
    memories: await db.memories.toArray(),
    exportedAt: new Date().toISOString(),
    version: '2.0',
  }
  const blob = await exportToJSON(data)
  await downloadBlob(blob, `ai-os-full-export-${Date.now()}.json`)
}

export async function generateInvoicePDF(invoice: Invoice): Promise<Blob> {
  const invoiceLines = invoice.items
    .map((item) => `${item.description}: ${item.quantity} x $${item.unitPrice.toFixed(2)} = $${item.total.toFixed(2)}`)
    .join('\n')

  const text = [
    `INVOICE #${invoice.number}`,
    `Client: ${invoice.clientName}`,
    `Status: ${invoice.status}`,
    `Due: ${invoice.dueDate}`,
    '',
    invoiceLines,
    '',
    `Subtotal: $${invoice.subtotal.toFixed(2)}`,
    `Tax: $${invoice.tax.toFixed(2)}`,
    `Total: $${invoice.total.toFixed(2)}`,
    '',
    `Generated by AI OS v2`,
  ].join('\n')

  return new Blob([text], { type: 'text/plain' })
}
